/**
 * Risk scoring and the friction ladder.
 *
 * Policy answers "may this happen". Risk answers "how hard should we make it
 * to say yes". Separating them matters: a permitted action can still be
 * dangerous, and friction is the only honest tool for that.
 *
 * Score is 0..100, additive, capped, and every contributing factor is
 * returned so the UI can explain the friction rather than just impose it.
 */

import { liquidCents, projectedBalanceCents } from './twin.mjs';
import { VERDICT } from './policy.mjs';

/**
 * @typedef {'low'|'moderate'|'elevated'|'high'} RiskBand
 * @typedef {'info'|'caution'|'warning'|'final_confirmation'} FrictionTier
 *
 * @typedef {Object} RiskFactor
 * @property {string} id
 * @property {string} label
 * @property {number} points
 * @property {string} detail
 *
 * @typedef {Object} RiskAssessment
 * @property {number} score 0..100
 * @property {RiskBand} band
 * @property {RiskFactor[]} factors
 * @property {FrictionTier} friction
 * @property {boolean} reversible
 */

const IRREVERSIBLE_KINDS = new Set(['invest', 'debt_payment']);

/**
 * @param {import('./policy.mjs').ProposedAction} action
 * @param {import('./twin.mjs').TwinSnapshot} twin
 * @param {import('./policy.mjs').Constitution} constitution
 * @param {import('./policy.mjs').Decision} decision
 * @returns {RiskAssessment}
 */
export function assess(action, twin, constitution, decision) {
  /** @type {RiskFactor[]} */
  const factors = [];
  const liquid = Math.max(liquidCents(twin), 1);

  // 1. Size relative to the user's actual liquidity, not an absolute number.
  const share = action.amountCents / liquid;
  if (share > 0.005) {
    const points = Math.min(30, Math.round(share * 100));
    factors.push({
      id: 'relative_size',
      label: 'Size relative to liquid cash',
      points,
      detail: `${(share * 100).toFixed(1)}% of your liquid cash.`,
    });
  }

  // 2. Proximity to the floor after the action — the thing users actually feel.
  if (action.sourceAccountId && action.kind !== 'policy_change') {
    const after =
      projectedBalanceCents(twin, action.sourceAccountId, constitution.shortTermHorizonDays) -
      action.amountCents;
    const headroom = after - constitution.cashFloorCents;
    if (headroom < 0) {
      factors.push({ id: 'below_floor', label: 'Breaches cash floor', points: 40, detail: `${fmtc(headroom)} below your floor.` });
    } else if (headroom < constitution.cashFloorCents * 0.25) {
      factors.push({ id: 'thin_headroom', label: 'Thin buffer', points: 20, detail: `Only ${fmtc(headroom)} above your floor afterwards.` });
    }
  }

  // 3. Reversibility.
  const reversible = !IRREVERSIBLE_KINDS.has(action.kind);
  if (!reversible) {
    factors.push({
      id: 'irreversible',
      label: 'Not easily reversible',
      points: 12,
      detail: action.kind === 'invest'
        ? 'Selling back may realize a loss or a taxable event.'
        : 'Payments to lenders generally cannot be recalled.',
    });
  }

  // 4. Novel destination.
  if (action.destinationAccountId && action.destinationKnown === false) {
    factors.push({ id: 'new_destination', label: 'First transfer to this destination', points: 18, detail: 'No prior transfer history.' });
  }

  // 5. Non-human origin.
  if (action.origin === 'ai') {
    factors.push({ id: 'ai_origin', label: 'Assistant-proposed', points: 8, detail: 'Generated by the assistant from your data, not requested by you.' });
  } else if (action.origin === 'automation') {
    factors.push({ id: 'automation_origin', label: 'Automated', points: 5, detail: 'Triggered by a standing rule.' });
  }

  // 6. Weakening a guardrail is categorically the most dangerous thing here.
  if (action.weakensProtection) {
    factors.push({ id: 'protection_downgrade', label: 'Removes a guardrail', points: 45, detail: 'Future automated actions gain more latitude.' });
  }

  const score = Math.min(100, factors.reduce((s, f) => s + f.points, 0));
  const band = score >= 60 ? 'high' : score >= 35 ? 'elevated' : score >= 15 ? 'moderate' : 'low';

  return { score, band, factors, friction: frictionFor(decision.verdict, band), reversible };
}

/**
 * The friction ladder: more risk, more friction — and never less friction than
 * the policy verdict demands.
 * @param {import('./policy.mjs').Verdict} verdict
 * @param {RiskBand} band
 * @returns {FrictionTier}
 */
export function frictionFor(verdict, band) {
  if (verdict === VERDICT.BLOCK) return 'warning';
  if (verdict === VERDICT.REQUIRE_REAUTH) return 'final_confirmation';
  if (band === 'high') return 'final_confirmation';
  if (band === 'elevated') return 'warning';
  if (band === 'moderate') return 'caution';
  return 'info';
}

function fmtc(c) {
  const neg = c < 0;
  const a = Math.abs(c);
  return `${neg ? '-' : ''}$${String(Math.floor(a / 100)).replace(/\B(?=(\d{3})+(?!\d))/g, ',')}.${String(a % 100).padStart(2, '0')}`;
}
